In [329]:
import pandas as pd

# From List

In [330]:
student_data = [
    ['Jehan',80,21],
    ['Hasan',99,52],
    ['Adib',56,21]
]
pd.DataFrame(student_data, columns=['Name','Marks','Age'])

    Name  Marks  Age
0  Jehan     80   21
1  Hasan     99   52
2   Adib     56   21

# From Dictionary

In [331]:
student_data = {
    'Name' : ['Jehan', 'Hasan', 'Adib'],
    'Marks' : [80, 99, 56],
    'Age' : [21, 52, 21]
}
pd.DataFrame(student_data)

    Name  Marks  Age
0  Jehan     80   21
1  Hasan     99   52
2   Adib     56   21

In [332]:
df = pd.read_csv('../../Data/Football_Player_Stats.csv',index_col='Player')
df

,Rk,Nation,Pos,Squad,Comp,Age,Born,MP,CrdY,CrdR,2CrdY,Goals,Shots,SoT,Assists
Player,,,,,,,,,,,,,,,
Max Aarons,1,ENG,DF,Norwich City,Premier League,22,2000,34,0.25,0.00,0.00,0.00,0.41,0.06,0.06
Yunis Abdelhamid,2,MAR,DF,Reims,Ligue 1,34,1987,34,0.15,0.03,0.00,0.06,0.54,0.18,0.00
Salis Abdul Samed,3,GHA,MF,Clermont Foot,Ligue 1,22,2000,31,0.44,0.11,0.07,0.04,0.66,0.18,0.00
Laurent Abergel,4,FRA,MF,Lorient,Ligue 1,29,1993,34,0.27,0.00,0.00,0.00,0.91,0.21,0.06
Charles Abi,5,FRA,FW,Saint-Étienne,Ligue 1,22,2000,1,0.00,0.00,0.00,0.00,0.00,0.00,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Federico Ceccherini,496,ITA,DF,Hellas Verona,Serie A,30,1992,34,0.46,0.04,0.04,0.04,0.42,0.08,0.00
Emil Ceide,497,NOR,FWDF,Sassuolo,Serie A,20,2001,6,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Zeki Çelik,498,TUR,DF,Lille,Ligue 1,25,1997,32,0.33,0.00,0.00,0.07,0.77,0.10,0.10
Fabien Centonze,499,FRA,DF,Metz,Ligue 1,26,1996,19,0.17,0.00,0.00,0.23,0.85,0.40,0.06
Luca Ceppitelli,500,ITA,DF,Cagliari,Serie A,32,1989,24,0.19,0.00,0.00,0.06,0.43,0.06,0.06

# Dataframe attribute

In [333]:
df.shape

(500, 15)

In [334]:
df.dtypes

Rk           int64
Nation      object
Pos         object
Squad       object
Comp        object
Age          int64
Born         int64
MP           int64
CrdY       float64
CrdR       float64
2CrdY      float64
Goals      float64
Shots      float64
SoT        float64
Assists    float64
dtype: object

In [335]:
df.index

Index(['Max Aarons', 'Yunis Abdelhamid', 'Salis Abdul Samed',
       'Laurent Abergel', 'Charles Abi', 'Dickson Abiama', 'Matthis Abline',
       'Tammy Abraham', 'Luis Abram', 'Francesco Acerbi',
       ...
       'Catena', 'Craig Cathcart', 'Edinson Cavani', 'Dani Ceballos',
       'Pietro Ceccaroni', 'Federico Ceccherini', 'Emil Ceide', 'Zeki Çelik',
       'Fabien Centonze', 'Luca Ceppitelli'],
      dtype='object', name='Player', length=500)

In [336]:
df.columns

Index(['Rk', 'Nation', 'Pos', 'Squad', 'Comp', 'Age', 'Born', 'MP', 'CrdY',
       'CrdR', '2CrdY', 'Goals', 'Shots', 'SoT', 'Assists'],
      dtype='object')

In [337]:
df.values

array([[1, 'ENG', 'DF', ..., 0.41, 0.06, 0.06],
       [2, 'MAR', 'DF', ..., 0.54, 0.18, 0.0],
       [3, 'GHA', 'MF', ..., 0.66, 0.18, 0.0],
       ...,
       [498, 'TUR', 'DF', ..., 0.77, 0.1, 0.1],
       [499, 'FRA', 'DF', ..., 0.85, 0.4, 0.06],
       [500, 'ITA', 'DF', ..., 0.43, 0.06, 0.06]], dtype=object)

In [338]:
df.head()

,Rk,Nation,Pos,Squad,Comp,Age,Born,MP,CrdY,CrdR,2CrdY,Goals,Shots,SoT,Assists
Player,,,,,,,,,,,,,,,
Max Aarons,1,ENG,DF,Norwich City,Premier League,22,2000,34,0.25,0.00,0.00,0.00,0.41,0.06,0.06
Yunis Abdelhamid,2,MAR,DF,Reims,Ligue 1,34,1987,34,0.15,0.03,0.00,0.06,0.54,0.18,0.00
Salis Abdul Samed,3,GHA,MF,Clermont Foot,Ligue 1,22,2000,31,0.44,0.11,0.07,0.04,0.66,0.18,0.00
Laurent Abergel,4,FRA,MF,Lorient,Ligue 1,29,1993,34,0.27,0.00,0.00,0.00,0.91,0.21,0.06
Charles Abi,5,FRA,FW,Saint-Étienne,Ligue 1,22,2000,1,0.00,0.00,0.00,0.00,0.00,0.00,0.00

In [339]:
df.tail()

,Rk,Nation,Pos,Squad,Comp,Age,Born,MP,CrdY,CrdR,2CrdY,Goals,Shots,SoT,Assists
Player,,,,,,,,,,,,,,,
Federico Ceccherini,496,ITA,DF,Hellas Verona,Serie A,30,1992,34,0.46,0.04,0.04,0.04,0.42,0.08,0.00
Emil Ceide,497,NOR,FWDF,Sassuolo,Serie A,20,2001,6,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Zeki Çelik,498,TUR,DF,Lille,Ligue 1,25,1997,32,0.33,0.00,0.00,0.07,0.77,0.10,0.10
Fabien Centonze,499,FRA,DF,Metz,Ligue 1,26,1996,19,0.17,0.00,0.00,0.23,0.85,0.40,0.06
Luca Ceppitelli,500,ITA,DF,Cagliari,Serie A,32,1989,24,0.19,0.00,0.00,0.06,0.43,0.06,0.06

In [340]:
df.sample(5)

,Rk,Nation,Pos,Squad,Comp,Age,Born,MP,CrdY,CrdR,2CrdY,Goals,Shots,SoT,Assists
Player,,,,,,,,,,,,,,,
Aymen Barkok,209,MAR,MFFW,Eint Frankfurt,Bundesliga,24,1998,5,0.00,0.00,0.00,0.00,1.11,0.56,0.00
Tolgay Arslan,125,GER,MF,Udinese,Serie A,31,1990,30,0.49,0.00,0.00,0.05,1.25,0.49,0.00
Benjamin Bourigeaud,356,FRA,FWMF,Rennes,Ligue 1,28,1994,38,0.06,0.00,0.00,0.31,1.52,0.59,0.34
Ibrahima Baldé,182,FRA,FWMF,Lens,Ligue 1,19,2003,4,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Federico Ceccherini,496,ITA,DF,Hellas Verona,Serie A,30,1992,34,0.46,0.04,0.04,0.04,0.42,0.08,0.00

In [341]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 500 entries, Max Aarons to Luca Ceppitelli
Data columns (total 15 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Rk       500 non-null    int64
 1   Nation   500 non-null    object
 2   Pos      500 non-null    object
 3   Squad    500 non-null    object
 4   Comp     500 non-null    object
 5   Age      500 non-null    int64
 6   Born     500 non-null    int64
 7   MP       500 non-null    int64
 8   CrdY     500 non-null    float64
 9   CrdR     500 non-null    float64
 10  2CrdY    500 non-null    float64
 11  Goals    500 non-null    float64
 12  Shots    500 non-null    float64
 13  SoT      500 non-null    float64
 14  Assists  500 non-null    float64
dtypes: float64(7), int64(4), object(4)
memory usage: 62.5+ KB

In [342]:
df.describe()

,Rk,Age,Born,MP,CrdY,CrdR,2CrdY,Goals,Shots,SoT,Assists
count,500.000000,500.0000,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000
mean,250.500000,26.0840,1995.428000,18.842000,0.200180,0.007100,0.003320,0.109280,1.202860,0.393340,0.088220
std,144.481833,4.6661,4.651461,11.770051,0.226039,0.026744,0.019113,0.228774,1.430507,0.674536,0.257428
min,1.000000,16.0000,1981.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,125.750000,22.7500,1992.000000,8.000000,0.000000,0.000000,0.000000,0.000000,0.290000,0.000000,0.000000
50%,250.500000,26.0000,1996.000000,19.000000,0.160000,0.000000,0.000000,0.000000,0.770000,0.190000,0.000000
75%,375.250000,30.0000,1999.000000,30.000000,0.290000,0.000000,0.000000,0.132500,1.822500,0.565000,0.112500
max,500.000000,40.0000,2005.000000,38.000000,1.670000,0.230000,0.220000,3.330000,15.000000,10.000000,5.000000

In [343]:
df.isnull()

,Rk,Nation,Pos,Squad,Comp,Age,Born,MP,CrdY,CrdR,2CrdY,Goals,Shots,SoT,Assists
Player,,,,,,,,,,,,,,,
Max Aarons,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Yunis Abdelhamid,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Salis Abdul Samed,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Laurent Abergel,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Charles Abi,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Federico Ceccherini,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Emil Ceide,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Zeki Çelik,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Fabien Centonze,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Luca Ceppitelli,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [344]:
df.isnull().sum()

Rk         0
Nation     0
Pos        0
Squad      0
Comp       0
Age        0
Born       0
MP         0
CrdY       0
CrdR       0
2CrdY      0
Goals      0
Shots      0
SoT        0
Assists    0
dtype: int64

In [345]:
df.duplicated()

Player
Max Aarons             False
Yunis Abdelhamid       False
Salis Abdul Samed      False
Laurent Abergel        False
Charles Abi            False
                       ...
Federico Ceccherini    False
Emil Ceide             False
Zeki Çelik             False
Fabien Centonze        False
Luca Ceppitelli        False
Length: 500, dtype: bool

In [346]:
df.duplicated().sum()

0

In [347]:
# rename colums
df.rename(columns={'CrdR':'Red'} ,inplace=True)
df

,Rk,Nation,Pos,Squad,Comp,Age,Born,MP,CrdY,Red,2CrdY,Goals,Shots,SoT,Assists
Player,,,,,,,,,,,,,,,
Max Aarons,1,ENG,DF,Norwich City,Premier League,22,2000,34,0.25,0.00,0.00,0.00,0.41,0.06,0.06
Yunis Abdelhamid,2,MAR,DF,Reims,Ligue 1,34,1987,34,0.15,0.03,0.00,0.06,0.54,0.18,0.00
Salis Abdul Samed,3,GHA,MF,Clermont Foot,Ligue 1,22,2000,31,0.44,0.11,0.07,0.04,0.66,0.18,0.00
Laurent Abergel,4,FRA,MF,Lorient,Ligue 1,29,1993,34,0.27,0.00,0.00,0.00,0.91,0.21,0.06
Charles Abi,5,FRA,FW,Saint-Étienne,Ligue 1,22,2000,1,0.00,0.00,0.00,0.00,0.00,0.00,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Federico Ceccherini,496,ITA,DF,Hellas Verona,Serie A,30,1992,34,0.46,0.04,0.04,0.04,0.42,0.08,0.00
Emil Ceide,497,NOR,FWDF,Sassuolo,Serie A,20,2001,6,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Zeki Çelik,498,TUR,DF,Lille,Ligue 1,25,1997,32,0.33,0.00,0.00,0.07,0.77,0.10,0.10
Fabien Centonze,499,FRA,DF,Metz,Ligue 1,26,1996,19,0.17,0.00,0.00,0.23,0.85,0.40,0.06
Luca Ceppitelli,500,ITA,DF,Cagliari,Serie A,32,1989,24,0.19,0.00,0.00,0.06,0.43,0.06,0.06

# Math method

In [348]:
df[['MP', 'CrdY','Red', '2CrdY', 'Goals', 'Shots', 'SoT', 'Assists']].sum()

MP         9421.00
CrdY        100.09
Red           3.55
2CrdY         1.66
Goals        54.64
Shots       601.43
SoT         196.67
Assists      44.11
dtype: float64

In [349]:
df[['MP', 'CrdY','Red', '2CrdY', 'Goals', 'Shots', 'SoT', 'Assists']].mean()

MP         18.84200
CrdY        0.20018
Red         0.00710
2CrdY       0.00332
Goals       0.10928
Shots       1.20286
SoT         0.39334
Assists     0.08822
dtype: float64

In [350]:
df[['MP', 'CrdY','Red', '2CrdY', 'Goals', 'Shots', 'SoT', 'Assists']].var()

MP         138.534104
CrdY         0.051094
Red          0.000715
2CrdY        0.000365
Goals        0.052337
Shots        2.046352
SoT          0.454999
Assists      0.066269
dtype: float64

# Select Columns

In [351]:
df['MP']

Player
Max Aarons             34
Yunis Abdelhamid       34
Salis Abdul Samed      31
Laurent Abergel        34
Charles Abi             1
                       ..
Federico Ceccherini    34
Emil Ceide              6
Zeki Çelik             32
Fabien Centonze        19
Luca Ceppitelli        24
Name: MP, Length: 500, dtype: int64

In [352]:
df[['MP', 'CrdY', 'Red', '2CrdY', 'Goals']]

                     MP  CrdY   Red  2CrdY  Goals
Player
Max Aarons           34  0.25  0.00   0.00   0.00
Yunis Abdelhamid     34  0.15  0.03   0.00   0.06
Salis Abdul Samed    31  0.44  0.11   0.07   0.04
Laurent Abergel      34  0.27  0.00   0.00   0.00
Charles Abi           1  0.00  0.00   0.00   0.00
...                  ..   ...   ...    ...    ...
Federico Ceccherini  34  0.46  0.04   0.04   0.04
Emil Ceide            6  0.00  0.00   0.00   0.00
Zeki Çelik           32  0.33  0.00   0.00   0.07
Fabien Centonze      19  0.17  0.00   0.00   0.23
Luca Ceppitelli      24  0.19  0.00   0.00   0.06

[500 rows x 5 columns]

# Select Row

In [353]:
df

,Rk,Nation,Pos,Squad,Comp,Age,Born,MP,CrdY,Red,2CrdY,Goals,Shots,SoT,Assists
Player,,,,,,,,,,,,,,,
Max Aarons,1,ENG,DF,Norwich City,Premier League,22,2000,34,0.25,0.00,0.00,0.00,0.41,0.06,0.06
Yunis Abdelhamid,2,MAR,DF,Reims,Ligue 1,34,1987,34,0.15,0.03,0.00,0.06,0.54,0.18,0.00
Salis Abdul Samed,3,GHA,MF,Clermont Foot,Ligue 1,22,2000,31,0.44,0.11,0.07,0.04,0.66,0.18,0.00
Laurent Abergel,4,FRA,MF,Lorient,Ligue 1,29,1993,34,0.27,0.00,0.00,0.00,0.91,0.21,0.06
Charles Abi,5,FRA,FW,Saint-Étienne,Ligue 1,22,2000,1,0.00,0.00,0.00,0.00,0.00,0.00,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Federico Ceccherini,496,ITA,DF,Hellas Verona,Serie A,30,1992,34,0.46,0.04,0.04,0.04,0.42,0.08,0.00
Emil Ceide,497,NOR,FWDF,Sassuolo,Serie A,20,2001,6,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Zeki Çelik,498,TUR,DF,Lille,Ligue 1,25,1997,32,0.33,0.00,0.00,0.07,0.77,0.10,0.10
Fabien Centonze,499,FRA,DF,Metz,Ligue 1,26,1996,19,0.17,0.00,0.00,0.23,0.85,0.40,0.06
Luca Ceppitelli,500,ITA,DF,Cagliari,Serie A,32,1989,24,0.19,0.00,0.00,0.06,0.43,0.06,0.06

In [354]:
df.iloc[5]

Rk                      6
Nation                NGA
Pos                    FW
Squad      Greuther Fürth
Comp           Bundesliga
Age                    23
Born                 1998
MP                     24
CrdY                 0.37
Red                   0.0
2CrdY                 0.0
Goals                 0.0
Shots                2.22
SoT                  0.49
Assists              0.12
Name: Dickson Abiama, dtype: object

In [355]:
df.iloc[3:6]

,Rk,Nation,Pos,Squad,Comp,Age,Born,MP,CrdY,Red,2CrdY,Goals,Shots,SoT,Assists
Player,,,,,,,,,,,,,,,
Laurent Abergel,4,FRA,MF,Lorient,Ligue 1,29,1993,34,0.27,0.0,0.0,0.0,0.91,0.21,0.06
Charles Abi,5,FRA,FW,Saint-Étienne,Ligue 1,22,2000,1,0.00,0.0,0.0,0.0,0.00,0.00,0.00
Dickson Abiama,6,NGA,FW,Greuther Fürth,Bundesliga,23,1998,24,0.37,0.0,0.0,0.0,2.22,0.49,0.12

In [356]:
df.iloc[[1,5,9,6]]

,Rk,Nation,Pos,Squad,Comp,Age,Born,MP,CrdY,Red,2CrdY,Goals,Shots,SoT,Assists
Player,,,,,,,,,,,,,,,
Yunis Abdelhamid,2,MAR,DF,Reims,Ligue 1,34,1987,34,0.15,0.03,0.0,0.06,0.54,0.18,0.00
Dickson Abiama,6,NGA,FW,Greuther Fürth,Bundesliga,23,1998,24,0.37,0.00,0.0,0.00,2.22,0.49,0.12
Francesco Acerbi,10,ITA,DF,Lazio,Serie A,34,1988,30,0.07,0.04,0.0,0.14,0.57,0.25,0.00
Matthis Abline,7,FRA,FW,Rennes,Ligue 1,19,2003,7,0.00,0.00,0.0,0.00,1.82,0.00,0.00

In [357]:
# using loc
df.loc['Yunis Abdelhamid']

Rk               2
Nation         MAR
Pos             DF
Squad        Reims
Comp       Ligue 1
Age             34
Born          1987
MP              34
CrdY          0.15
Red           0.03
2CrdY          0.0
Goals         0.06
Shots         0.54
SoT           0.18
Assists        0.0
Name: Yunis Abdelhamid, dtype: object

In [358]:
df.loc['Yunis Abdelhamid' : 'Dickson Abiama']

,Rk,Nation,Pos,Squad,Comp,Age,Born,MP,CrdY,Red,2CrdY,Goals,Shots,SoT,Assists
Player,,,,,,,,,,,,,,,
Yunis Abdelhamid,2,MAR,DF,Reims,Ligue 1,34,1987,34,0.15,0.03,0.00,0.06,0.54,0.18,0.00
Salis Abdul Samed,3,GHA,MF,Clermont Foot,Ligue 1,22,2000,31,0.44,0.11,0.07,0.04,0.66,0.18,0.00
Laurent Abergel,4,FRA,MF,Lorient,Ligue 1,29,1993,34,0.27,0.00,0.00,0.00,0.91,0.21,0.06
Charles Abi,5,FRA,FW,Saint-Étienne,Ligue 1,22,2000,1,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Dickson Abiama,6,NGA,FW,Greuther Fürth,Bundesliga,23,1998,24,0.37,0.00,0.00,0.00,2.22,0.49,0.12

In [359]:
df.loc[['Yunis Abdelhamid' , 'Salis Abdul Samed', 'Dickson Abiama']]

,Rk,Nation,Pos,Squad,Comp,Age,Born,MP,CrdY,Red,2CrdY,Goals,Shots,SoT,Assists
Player,,,,,,,,,,,,,,,
Yunis Abdelhamid,2,MAR,DF,Reims,Ligue 1,34,1987,34,0.15,0.03,0.00,0.06,0.54,0.18,0.00
Salis Abdul Samed,3,GHA,MF,Clermont Foot,Ligue 1,22,2000,31,0.44,0.11,0.07,0.04,0.66,0.18,0.00
Dickson Abiama,6,NGA,FW,Greuther Fürth,Bundesliga,23,1998,24,0.37,0.00,0.00,0.00,2.22,0.49,0.12

# Select row and cols

In [360]:
df.iloc[2:5 , 5:9]

                   Age  Born  MP  CrdY
Player
Salis Abdul Samed   22  2000  31  0.44
Laurent Abergel     29  1993  34  0.27
Charles Abi         22  2000   1  0.00

# Boolean Indexing

In [361]:
df['Age'] > 30

Player
Max Aarons             False
Yunis Abdelhamid        True
Salis Abdul Samed      False
Laurent Abergel        False
Charles Abi            False
                       ...
Federico Ceccherini    False
Emil Ceide             False
Zeki Çelik             False
Fabien Centonze        False
Luca Ceppitelli         True
Name: Age, Length: 500, dtype: bool

In [362]:
df[ df['Age'] > 30 ]

,Rk,Nation,Pos,Squad,Comp,Age,Born,MP,CrdY,Red,2CrdY,Goals,Shots,SoT,Assists
Player,,,,,,,,,,,,,,,
Yunis Abdelhamid,2,MAR,DF,Reims,Ligue 1,34,1987,34,0.15,0.03,0.0,0.06,0.54,0.18,0.00
Francesco Acerbi,10,ITA,DF,Lazio,Serie A,34,1988,30,0.07,0.04,0.0,0.14,0.57,0.25,0.00
Sergio Agüero,27,ARG,FW,Barcelona,La Liga,33,1988,4,0.00,0.00,0.0,0.59,3.53,0.59,0.00
Jordi Alba,51,ESP,DF,Barcelona,La Liga,33,1989,30,0.37,0.00,0.0,0.07,1.05,0.20,0.34
Raúl Albiol,54,ESP,DF,Villarreal,La Liga,36,1985,28,0.29,0.00,0.0,0.00,0.22,0.04,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Kiko Casilla,480,ESP,GK,Elche,La Liga,35,1986,14,0.21,0.00,0.0,0.00,0.00,0.00,0.00
Gonzalo Castro,487,GER,MFFW,Arminia,Bundesliga,34,1987,12,0.00,0.00,0.0,0.21,1.67,0.42,0.21
Craig Cathcart,492,NIR,DF,Watford,Premier League,33,1989,31,0.11,0.00,0.0,0.00,0.11,0.00,0.04
Edinson Cavani,493,URU,FW,Manchester Utd,Premier League,35,1987,15,0.00,0.00,0.0,0.24,2.12,0.71,0.12
Luca Ceppitelli,500,ITA,DF,Cagliari,Serie A,32,1989,24,0.19,0.00,0.0,0.06,0.43,0.06,0.06

In [363]:
df[ (df['Age'] > 30) & (df['Pos'] == 'DF') ]

,Rk,Nation,Pos,Squad,Comp,Age,Born,MP,CrdY,Red,2CrdY,Goals,Shots,SoT,Assists
Player,,,,,,,,,,,,,,,
Yunis Abdelhamid,2,MAR,DF,Reims,Ligue 1,34,1987,34,0.15,0.03,0.0,0.06,0.54,0.18,0.00
Francesco Acerbi,10,ITA,DF,Lazio,Serie A,34,1988,30,0.07,0.04,0.0,0.14,0.57,0.25,0.00
Jordi Alba,51,ESP,DF,Barcelona,La Liga,33,1989,30,0.37,0.00,0.0,0.07,1.05,0.20,0.34
Raúl Albiol,54,ESP,DF,Villarreal,La Liga,36,1985,28,0.29,0.00,0.0,0.00,0.22,0.04,0.00
Marcos Alonso,72,ESP,DF,Chelsea,Premier League,31,1990,28,0.33,0.00,0.0,0.17,1.78,0.41,0.17
Dani Alves,76,BRA,DF,Barcelona,La Liga,39,1983,14,0.16,0.08,0.0,0.08,0.41,0.16,0.25
José Ángel,98,ESP,DF,Osasuna,La Liga,32,1989,23,0.17,0.08,0.0,0.08,0.92,0.25,0.08
Cristian Ansaldi,101,ARG,DF,Torino,Serie A,35,1986,19,0.26,0.00,0.0,0.00,0.91,0.13,0.39
Ramzi Aya,150,ITA,DF,Salernitana,Serie A,31,1990,2,0.67,0.00,0.0,0.00,0.67,0.00,0.00
Karim Azamoum,154,FRA,DF,Troyes,Ligue 1,32,1990,7,0.47,0.00,0.0,0.00,0.70,0.70,0.00
César Azpilicueta,156,ESP,DF,Chelsea,Premier League,32,1989,27,0.13,0.00,0.0,0.04,0.57,0.17,0.09
Mikel Balenziaga,185,ESP,DF,Athletic Club,La Liga,34,1988,26,0.09,0.00,0.0,0.00,0.27,0.09,0.00
Abdoulaye Bamba,190,CIV,DF,Angers,Ligue 1,32,1990,10,0.20,0.00,0.0,0.00,0.20,0.00,0.00
Antonio Barragán,212,ESP,DF,Elche,La Liga,34,1987,16,0.44,0.00,0.0,0.00,0.09,0.00,0.00
Marc Bartra,218,ESP,DF,Betis,La Liga,31,1991,23,0.23,0.00,0.0,0.05,0.68,0.14,0.00
Paul Baysse,236,FRA,DF,Bordeaux,Ligue 1,34,1988,2,0.00,0.00,0.0,0.00,0.00,0.00,0.00
Yuri Berchiche,288,ESP,DF,Athletic Club,La Liga,32,1990,14,0.27,0.00,0.0,0.09,0.71,0.27,0.18
Ryan Bertrand,304,ENG,DF,Leicester City,Premier League,32,1989,4,0.27,0.00,0.0,0.00,0.00,0.00,0.00
Ermin Bi?ak?i?,310,BIH,DF,Hoffenheim,Bundesliga,32,1990,1,0.00,0.00,0.0,0.00,0.00,0.00,0.00
Pedro Bigas,312,ESP,DF,Elche,La Liga,31,1990,19,0.35,0.00,0.0,0.06,0.70,0.17,0.00
Jérôme Boateng,327,GER,DF,Lyon,Ligue 1,33,1988,24,0.33,0.00,0.0,0.00,0.28,0.17,0.06
Willy Boly,338,CIV,DF,Wolves,Premier League,31,1991,10,0.10,0.00,0.0,0.00,0.20,0.10,0.00
Leonardo Bonucci,344,ITA,DF,Juventus,Serie A,35,1987,24,0.04,0.00,0.0,0.22,0.63,0.13,0.00
Dedryck Boyata,360,BEL,DF,Hertha BSC,Bundesliga,31,1990,23,0.05,0.05,0.0,0.00,0.47,0.09,0.00
Daniel Brosinski,382,GER,DF,Mainz 05,Bundesliga,33,1988,11,0.00,0.00,0.0,0.00,0.23,0.00,0.00
Martín Cáceres,417,URU,DF,Cagliari,Serie A,35,1987,14,0.33,0.11,0.0,0.11,0.76,0.11,0.11
Martín Cáceres,418,URU,DF,Levante,La Liga,35,1987,10,0.27,0.00,0.0,0.00,0.00,0.00,0.00
Cala,427,ESP,DF,Cádiz,La Liga,32,1989,14,0.76,0.10,0.1,0.00,0.48,0.00,0.00
Craig Cathcart,492,NIR,DF,Watford,Premier League,33,1989,31,0.11,0.00,0.0,0.00,0.11,0.00,0.04
Luca Ceppitelli,500,ITA,DF,Cagliari,Serie A,32,1989,24,0.19,0.00,0.0,0.06,0.43,0.06,0.06

In [364]:
df.notnull()

,Rk,Nation,Pos,Squad,Comp,Age,Born,MP,CrdY,Red,2CrdY,Goals,Shots,SoT,Assists
Player,,,,,,,,,,,,,,,
Max Aarons,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
Yunis Abdelhamid,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
Salis Abdul Samed,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
Laurent Abergel,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
Charles Abi,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Federico Ceccherini,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
Emil Ceide,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
Zeki Çelik,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
Fabien Centonze,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
Luca Ceppitelli,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True

In [365]:
df[ df.notnull() ]

,Rk,Nation,Pos,Squad,Comp,Age,Born,MP,CrdY,Red,2CrdY,Goals,Shots,SoT,Assists
Player,,,,,,,,,,,,,,,
Max Aarons,1,ENG,DF,Norwich City,Premier League,22,2000,34,0.25,0.00,0.00,0.00,0.41,0.06,0.06
Yunis Abdelhamid,2,MAR,DF,Reims,Ligue 1,34,1987,34,0.15,0.03,0.00,0.06,0.54,0.18,0.00
Salis Abdul Samed,3,GHA,MF,Clermont Foot,Ligue 1,22,2000,31,0.44,0.11,0.07,0.04,0.66,0.18,0.00
Laurent Abergel,4,FRA,MF,Lorient,Ligue 1,29,1993,34,0.27,0.00,0.00,0.00,0.91,0.21,0.06
Charles Abi,5,FRA,FW,Saint-Étienne,Ligue 1,22,2000,1,0.00,0.00,0.00,0.00,0.00,0.00,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Federico Ceccherini,496,ITA,DF,Hellas Verona,Serie A,30,1992,34,0.46,0.04,0.04,0.04,0.42,0.08,0.00
Emil Ceide,497,NOR,FWDF,Sassuolo,Serie A,20,2001,6,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Zeki Çelik,498,TUR,DF,Lille,Ligue 1,25,1997,32,0.33,0.00,0.00,0.07,0.77,0.10,0.10
Fabien Centonze,499,FRA,DF,Metz,Ligue 1,26,1996,19,0.17,0.00,0.00,0.23,0.85,0.40,0.06
Luca Ceppitelli,500,ITA,DF,Cagliari,Serie A,32,1989,24,0.19,0.00,0.00,0.06,0.43,0.06,0.06

# Adding new col

In [366]:
df['is_player'] = True
df

,Rk,Nation,Pos,Squad,Comp,Age,Born,MP,CrdY,Red,2CrdY,Goals,Shots,SoT,Assists,is_player
Player,,,,,,,,,,,,,,,,
Max Aarons,1,ENG,DF,Norwich City,Premier League,22,2000,34,0.25,0.00,0.00,0.00,0.41,0.06,0.06,True
Yunis Abdelhamid,2,MAR,DF,Reims,Ligue 1,34,1987,34,0.15,0.03,0.00,0.06,0.54,0.18,0.00,True
Salis Abdul Samed,3,GHA,MF,Clermont Foot,Ligue 1,22,2000,31,0.44,0.11,0.07,0.04,0.66,0.18,0.00,True
Laurent Abergel,4,FRA,MF,Lorient,Ligue 1,29,1993,34,0.27,0.00,0.00,0.00,0.91,0.21,0.06,True
Charles Abi,5,FRA,FW,Saint-Étienne,Ligue 1,22,2000,1,0.00,0.00,0.00,0.00,0.00,0.00,0.00,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Federico Ceccherini,496,ITA,DF,Hellas Verona,Serie A,30,1992,34,0.46,0.04,0.04,0.04,0.42,0.08,0.00,True
Emil Ceide,497,NOR,FWDF,Sassuolo,Serie A,20,2001,6,0.00,0.00,0.00,0.00,0.00,0.00,0.00,True
Zeki Çelik,498,TUR,DF,Lille,Ligue 1,25,1997,32,0.33,0.00,0.00,0.07,0.77,0.10,0.10,True
Fabien Centonze,499,FRA,DF,Metz,Ligue 1,26,1996,19,0.17,0.00,0.00,0.23,0.85,0.40,0.06,True
Luca Ceppitelli,500,ITA,DF,Cagliari,Serie A,32,1989,24,0.19,0.00,0.00,0.06,0.43,0.06,0.06,True

# Remove null value

In [367]:
df.dropna(inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 500 entries, Max Aarons to Luca Ceppitelli
Data columns (total 16 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Rk         500 non-null    int64
 1   Nation     500 non-null    object
 2   Pos        500 non-null    object
 3   Squad      500 non-null    object
 4   Comp       500 non-null    object
 5   Age        500 non-null    int64
 6   Born       500 non-null    int64
 7   MP         500 non-null    int64
 8   CrdY       500 non-null    float64
 9   Red        500 non-null    float64
 10  2CrdY      500 non-null    float64
 11  Goals      500 non-null    float64
 12  Shots      500 non-null    float64
 13  SoT        500 non-null    float64
 14  Assists    500 non-null    float64
 15  is_player  500 non-null    bool
dtypes: bool(1), float64(7), int64(4), object(4)
memory usage: 79.2+ KB

# change attribute type

In [368]:
df['SoT'] = df['SoT'].astype('float32')
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 500 entries, Max Aarons to Luca Ceppitelli
Data columns (total 16 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Rk         500 non-null    int64
 1   Nation     500 non-null    object
 2   Pos        500 non-null    object
 3   Squad      500 non-null    object
 4   Comp       500 non-null    object
 5   Age        500 non-null    int64
 6   Born       500 non-null    int64
 7   MP         500 non-null    int64
 8   CrdY       500 non-null    float64
 9   Red        500 non-null    float64
 10  2CrdY      500 non-null    float64
 11  Goals      500 non-null    float64
 12  Shots      500 non-null    float64
 13  SoT        500 non-null    float32
 14  Assists    500 non-null    float64
 15  is_player  500 non-null    bool
dtypes: bool(1), float32(1), float64(6), int64(4), object(4)
memory usage: 77.2+ KB

# Some Function

In [369]:
df.value_counts()

Rk   Nation  Pos  Squad         Comp            Age  Born  MP  CrdY  Red   2CrdY  Goals  Shots  SoT   Assists  is_player
1    ENG     DF   Norwich City  Premier League  22   2000  34  0.25  0.00  0.00   0.00   0.41   0.06  0.06     True         1
330  GER     DF   Bochum        Bundesliga      27   1995  18  0.11  0.00  0.00   0.00   0.74   0.21  0.00     True         1
343  NED     DF   RB Leipzig    Bundesliga      18   2003  1   0.00  0.00  0.00   0.00   0.00   0.00  0.00     True         1
342  ITA     DF   Bologna       Serie A         26   1996  22  0.30  0.07  0.07   0.00   0.67   0.00  0.00     True         1
341  GER     FW   Bochum        Bundesliga      25   1997  3   0.00  0.00  0.00   0.00   15.00  5.00  0.00     True         1
                                                                                                                           ..
162  ESP     GK   Elche         La Liga         30   1992  24  0.08  0.00  0.00   0.00   0.00   0.00  0.00     True         1
161  CRO     MF   Genoa         Serie A         33   1989  34  0.13  0.00  0.00   0.03   0.70   0.16  0.00     True         1
160  FRA     DF   Rennes        Ligue 1         22   2000  14  0.28  0.09  0.09   0.00   0.64   0.00  0.09     True         1
159  AUT     GK   Watford       Premier League  27   1994  12  0.00  0.00  0.00   0.00   0.00   0.00  0.00     True         1
500  ITA     DF   Cagliari      Serie A         32   1989  24  0.19  0.00  0.00   0.06   0.43   0.06  0.06     True         1
Name: count, Length: 500, dtype: int64

In [370]:
df.sort_values(by='Age')

,Rk,Nation,Pos,Squad,Comp,Age,Born,MP,CrdY,Red,2CrdY,Goals,Shots,SoT,Assists,is_player
Player,,,,,,,,,,,,,,,,
Tom Bischof,318,GER,MFFW,Hoffenheim,Bundesliga,16,2005,1,0.00,0.00,0.0,0.00,0.00,0.00,0.00,True
Wisdom Amey,84,ITA,DF,Bologna,Serie A,16,2005,1,0.00,0.00,0.0,0.00,0.00,0.00,0.00,True
Jamie Bynoe-Gittens,408,ENG,FW,Dortmund,Bundesliga,17,2004,4,0.00,0.00,0.0,0.00,0.67,0.67,0.00,True
Iker Bravo,371,ESP,FW,Leverkusen,Bundesliga,17,2005,1,0.00,0.00,0.0,0.00,0.00,0.00,0.00,True
Jeanuel Belocian,261,FRA,DF,Rennes,Ligue 1,17,2005,1,0.00,0.00,0.0,0.00,0.00,0.00,0.00,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Valon Behrami,247,SUI,MF,Genoa,Serie A,37,1985,10,0.86,0.00,0.0,0.00,0.29,0.00,0.00,True
Yannick Cahuzac,421,FRA,MF,Lens,Ligue 1,37,1985,17,0.14,0.14,0.0,0.00,0.14,0.00,0.00,True
Dani Alves,76,BRA,DF,Barcelona,La Liga,39,1983,14,0.16,0.08,0.0,0.08,0.41,0.16,0.25,True
Claudio Bravo,370,CHI,GK,Betis,La Liga,39,1983,17,0.12,0.00,0.0,0.00,0.00,0.00,0.00,True
Willy Caballero,411,ARG,GK,Southampton,Premier League,40,1981,2,0.50,0.00,0.0,0.00,0.00,0.00,0.00,True

In [371]:
df['rank'] = df['Goals'].rank(ascending=False)
df.sort_values(by='rank')

,Rk,Nation,Pos,Squad,Comp,Age,Born,MP,CrdY,Red,2CrdY,Goals,Shots,SoT,Assists,is_player,rank
Player,,,,,,,,,,,,,,,,,
Delano Burgzorg,396,NED,FW,Mainz 05,Bundesliga,23,1998,3,0.00,0.0,0.0,3.33,6.67,3.33,0.00,True,1.0
Donny van de Beek,244,NED,MF,Manchester Utd,Premier League,25,1997,8,0.00,0.0,0.0,1.25,2.50,1.25,0.00,True,2.5
Edoardo Bove,358,ITA,MFFW,Roma,Serie A,20,2002,11,0.00,0.0,0.0,1.25,1.25,1.25,0.00,True,2.5
Cédric Bakambu,174,COD,FW,Marseille,Ligue 1,31,1991,12,0.25,0.0,0.0,1.00,4.75,2.00,0.00,True,4.0
Karim Benzema,285,FRA,FW,Real Madrid,La Liga,34,1987,32,0.00,0.0,0.0,0.94,4.10,1.63,0.42,True,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Toma Bai?,221,CRO,MF,Lazio,Serie A,25,1996,29,0.28,0.0,0.0,0.00,1.47,1.01,0.18,True,374.0
Daniele Baselli,220,ITA,MF,Cagliari,Serie A,30,1992,9,0.31,0.0,0.0,0.00,1.56,0.00,0.31,True,374.0
Daniele Baselli,219,ITA,MFFW,Torino,Serie A,30,1992,6,0.00,0.0,0.0,0.00,0.59,0.00,0.00,True,374.0
Maximilian Bauer,229,GER,DF,Greuther Fürth,Bundesliga,22,2000,26,0.27,0.0,0.0,0.00,0.32,0.05,0.00,True,374.0
Vid Belec,250,SVN,GK,Salernitana,Serie A,31,1990,23,0.05,0.0,0.0,0.00,0.00,0.00,0.00,True,374.0

In [372]:
df.sort_index()

,Rk,Nation,Pos,Squad,Comp,Age,Born,MP,CrdY,Red,2CrdY,Goals,Shots,SoT,Assists,is_player,rank
Player,,,,,,,,,,,,,,,,,
Abdoulaye Bakayoko,175,FRA,DF,Saint-Étienne,Ligue 1,19,2002,4,0.00,0.0,0.0,0.00,0.00,0.00,0.00,True,374.0
Abdoulaye Bamba,190,CIV,DF,Angers,Ligue 1,32,1990,10,0.20,0.0,0.0,0.00,0.20,0.00,0.00,True,374.0
Abdourahmane Barry,217,FRA,DF,Greuther Fürth,Bundesliga,22,2000,8,0.87,0.0,0.0,0.00,0.43,0.00,0.00,True,374.0
Adam Armstrong,120,ENG,FW,Southampton,Premier League,25,1997,23,0.06,0.0,0.0,0.13,2.99,0.89,0.13,True,127.5
Adil Aouchiche,108,FRA,MFFW,Saint-Étienne,Ligue 1,19,2002,35,0.17,0.0,0.0,0.00,1.83,0.83,0.33,True,374.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Álex Cantero,455,ESP,FWMF,Levante,La Liga,21,2000,25,0.15,0.0,0.0,0.00,2.35,0.74,0.15,True,374.0
Álvaro Aguirre,29,ESP,FW,Rayo Vallecano,La Liga,22,2000,1,0.00,0.0,0.0,0.00,0.00,0.00,0.00,True,374.0
Álvaro Bastida,224,ESP,MF,Cádiz,La Liga,18,2004,6,0.45,0.0,0.0,0.00,0.00,0.00,0.00,True,374.0
Édgar Badía,162,ESP,GK,Elche,La Liga,30,1992,24,0.08,0.0,0.0,0.00,0.00,0.00,0.00,True,374.0
Étienne Capoue,460,FRA,MF,Villarreal,La Liga,33,1988,30,0.35,0.0,0.0,0.04,0.55,0.20,0.04,True,229.0

In [373]:
df = df.reset_index()
df

,Player,Rk,Nation,Pos,Squad,Comp,Age,Born,MP,CrdY,Red,2CrdY,Goals,Shots,SoT,Assists,is_player,rank
0,Max Aarons,1,ENG,DF,Norwich City,Premier League,22,2000,34,0.25,0.00,0.00,0.00,0.41,0.06,0.06,True,374.0
1,Yunis Abdelhamid,2,MAR,DF,Reims,Ligue 1,34,1987,34,0.15,0.03,0.00,0.06,0.54,0.18,0.00,True,195.5
2,Salis Abdul Samed,3,GHA,MF,Clermont Foot,Ligue 1,22,2000,31,0.44,0.11,0.07,0.04,0.66,0.18,0.00,True,229.0
3,Laurent Abergel,4,FRA,MF,Lorient,Ligue 1,29,1993,34,0.27,0.00,0.00,0.00,0.91,0.21,0.06,True,374.0
4,Charles Abi,5,FRA,FW,Saint-Étienne,Ligue 1,22,2000,1,0.00,0.00,0.00,0.00,0.00,0.00,0.00,True,374.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,Federico Ceccherini,496,ITA,DF,Hellas Verona,Serie A,30,1992,34,0.46,0.04,0.04,0.04,0.42,0.08,0.00,True,229.0
496,Emil Ceide,497,NOR,FWDF,Sassuolo,Serie A,20,2001,6,0.00,0.00,0.00,0.00,0.00,0.00,0.00,True,374.0
497,Zeki Çelik,498,TUR,DF,Lille,Ligue 1,25,1997,32,0.33,0.00,0.00,0.07,0.77,0.10,0.10,True,179.5
498,Fabien Centonze,499,FRA,DF,Metz,Ligue 1,26,1996,19,0.17,0.00,0.00,0.23,0.85,0.40,0.06,True,81.5
499,Luca Ceppitelli,500,ITA,DF,Cagliari,Serie A,32,1989,24,0.19,0.00,0.00,0.06,0.43,0.06,0.06,True,195.5

In [374]:
df.set_index('Player')

,Rk,Nation,Pos,Squad,Comp,Age,Born,MP,CrdY,Red,2CrdY,Goals,Shots,SoT,Assists,is_player,rank
Player,,,,,,,,,,,,,,,,,
Max Aarons,1,ENG,DF,Norwich City,Premier League,22,2000,34,0.25,0.00,0.00,0.00,0.41,0.06,0.06,True,374.0
Yunis Abdelhamid,2,MAR,DF,Reims,Ligue 1,34,1987,34,0.15,0.03,0.00,0.06,0.54,0.18,0.00,True,195.5
Salis Abdul Samed,3,GHA,MF,Clermont Foot,Ligue 1,22,2000,31,0.44,0.11,0.07,0.04,0.66,0.18,0.00,True,229.0
Laurent Abergel,4,FRA,MF,Lorient,Ligue 1,29,1993,34,0.27,0.00,0.00,0.00,0.91,0.21,0.06,True,374.0
Charles Abi,5,FRA,FW,Saint-Étienne,Ligue 1,22,2000,1,0.00,0.00,0.00,0.00,0.00,0.00,0.00,True,374.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Federico Ceccherini,496,ITA,DF,Hellas Verona,Serie A,30,1992,34,0.46,0.04,0.04,0.04,0.42,0.08,0.00,True,229.0
Emil Ceide,497,NOR,FWDF,Sassuolo,Serie A,20,2001,6,0.00,0.00,0.00,0.00,0.00,0.00,0.00,True,374.0
Zeki Çelik,498,TUR,DF,Lille,Ligue 1,25,1997,32,0.33,0.00,0.00,0.07,0.77,0.10,0.10,True,179.5
Fabien Centonze,499,FRA,DF,Metz,Ligue 1,26,1996,19,0.17,0.00,0.00,0.23,0.85,0.40,0.06,True,81.5
Luca Ceppitelli,500,ITA,DF,Cagliari,Serie A,32,1989,24,0.19,0.00,0.00,0.06,0.43,0.06,0.06,True,195.5

In [375]:
df.nunique()

Player       479
Rk           500
Nation        67
Pos           10
Squad         95
Comp           5
Age           24
Born          23
MP            38
CrdY          75
Red           16
2CrdY         11
Goals         59
Shots        210
SoT          122
Assists       48
is_player      1
rank          59
dtype: int64

In [376]:
df.drop_duplicates(inplace=True)
df

,Player,Rk,Nation,Pos,Squad,Comp,Age,Born,MP,CrdY,Red,2CrdY,Goals,Shots,SoT,Assists,is_player,rank
0,Max Aarons,1,ENG,DF,Norwich City,Premier League,22,2000,34,0.25,0.00,0.00,0.00,0.41,0.06,0.06,True,374.0
1,Yunis Abdelhamid,2,MAR,DF,Reims,Ligue 1,34,1987,34,0.15,0.03,0.00,0.06,0.54,0.18,0.00,True,195.5
2,Salis Abdul Samed,3,GHA,MF,Clermont Foot,Ligue 1,22,2000,31,0.44,0.11,0.07,0.04,0.66,0.18,0.00,True,229.0
3,Laurent Abergel,4,FRA,MF,Lorient,Ligue 1,29,1993,34,0.27,0.00,0.00,0.00,0.91,0.21,0.06,True,374.0
4,Charles Abi,5,FRA,FW,Saint-Étienne,Ligue 1,22,2000,1,0.00,0.00,0.00,0.00,0.00,0.00,0.00,True,374.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,Federico Ceccherini,496,ITA,DF,Hellas Verona,Serie A,30,1992,34,0.46,0.04,0.04,0.04,0.42,0.08,0.00,True,229.0
496,Emil Ceide,497,NOR,FWDF,Sassuolo,Serie A,20,2001,6,0.00,0.00,0.00,0.00,0.00,0.00,0.00,True,374.0
497,Zeki Çelik,498,TUR,DF,Lille,Ligue 1,25,1997,32,0.33,0.00,0.00,0.07,0.77,0.10,0.10,True,179.5
498,Fabien Centonze,499,FRA,DF,Metz,Ligue 1,26,1996,19,0.17,0.00,0.00,0.23,0.85,0.40,0.06,True,81.5
499,Luca Ceppitelli,500,ITA,DF,Cagliari,Serie A,32,1989,24,0.19,0.00,0.00,0.06,0.43,0.06,0.06,True,195.5

In [377]:
df.drop(columns=['Rk','Born'], inplace=True)
df = df.set_index('Player')
df

,Nation,Pos,Squad,Comp,Age,MP,CrdY,Red,2CrdY,Goals,Shots,SoT,Assists,is_player,rank
Player,,,,,,,,,,,,,,,
Max Aarons,ENG,DF,Norwich City,Premier League,22,34,0.25,0.00,0.00,0.00,0.41,0.06,0.06,True,374.0
Yunis Abdelhamid,MAR,DF,Reims,Ligue 1,34,34,0.15,0.03,0.00,0.06,0.54,0.18,0.00,True,195.5
Salis Abdul Samed,GHA,MF,Clermont Foot,Ligue 1,22,31,0.44,0.11,0.07,0.04,0.66,0.18,0.00,True,229.0
Laurent Abergel,FRA,MF,Lorient,Ligue 1,29,34,0.27,0.00,0.00,0.00,0.91,0.21,0.06,True,374.0
Charles Abi,FRA,FW,Saint-Étienne,Ligue 1,22,1,0.00,0.00,0.00,0.00,0.00,0.00,0.00,True,374.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Federico Ceccherini,ITA,DF,Hellas Verona,Serie A,30,34,0.46,0.04,0.04,0.04,0.42,0.08,0.00,True,229.0
Emil Ceide,NOR,FWDF,Sassuolo,Serie A,20,6,0.00,0.00,0.00,0.00,0.00,0.00,0.00,True,374.0
Zeki Çelik,TUR,DF,Lille,Ligue 1,25,32,0.33,0.00,0.00,0.07,0.77,0.10,0.10,True,179.5
Fabien Centonze,FRA,DF,Metz,Ligue 1,26,19,0.17,0.00,0.00,0.23,0.85,0.40,0.06,True,81.5
Luca Ceppitelli,ITA,DF,Cagliari,Serie A,32,24,0.19,0.00,0.00,0.06,0.43,0.06,0.06,True,195.5

In [378]:
df.drop(index=['Yunis Abdelhamid','Laurent Abergel'], inplace=True)
df

,Nation,Pos,Squad,Comp,Age,MP,CrdY,Red,2CrdY,Goals,Shots,SoT,Assists,is_player,rank
Player,,,,,,,,,,,,,,,
Max Aarons,ENG,DF,Norwich City,Premier League,22,34,0.25,0.00,0.00,0.00,0.41,0.06,0.06,True,374.0
Salis Abdul Samed,GHA,MF,Clermont Foot,Ligue 1,22,31,0.44,0.11,0.07,0.04,0.66,0.18,0.00,True,229.0
Charles Abi,FRA,FW,Saint-Étienne,Ligue 1,22,1,0.00,0.00,0.00,0.00,0.00,0.00,0.00,True,374.0
Dickson Abiama,NGA,FW,Greuther Fürth,Bundesliga,23,24,0.37,0.00,0.00,0.00,2.22,0.49,0.12,True,374.0
Matthis Abline,FRA,FW,Rennes,Ligue 1,19,7,0.00,0.00,0.00,0.00,1.82,0.00,0.00,True,374.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Federico Ceccherini,ITA,DF,Hellas Verona,Serie A,30,34,0.46,0.04,0.04,0.04,0.42,0.08,0.00,True,229.0
Emil Ceide,NOR,FWDF,Sassuolo,Serie A,20,6,0.00,0.00,0.00,0.00,0.00,0.00,0.00,True,374.0
Zeki Çelik,TUR,DF,Lille,Ligue 1,25,32,0.33,0.00,0.00,0.07,0.77,0.10,0.10,True,179.5
Fabien Centonze,FRA,DF,Metz,Ligue 1,26,19,0.17,0.00,0.00,0.23,0.85,0.40,0.06,True,81.5
Luca Ceppitelli,ITA,DF,Cagliari,Serie A,32,24,0.19,0.00,0.00,0.06,0.43,0.06,0.06,True,195.5

# apply

In [380]:
points_df = pd.DataFrame(
    {
        '1st point':[(3,4),(-6,5),(0,0),(-10,1),(4,5)],
        '2nd point':[(-3,4),(0,0),(2,2),(10,10),(1,1)]
    }
)
points_df

  1st point 2nd point
0    (3, 4)   (-3, 4)
1   (-6, 5)    (0, 0)
2    (0, 0)    (2, 2)
3  (-10, 1)  (10, 10)
4    (4, 5)    (1, 1)

In [384]:
def euclidian_distance(row):
    p1 = row['1st point'] 
    p2 = row['2nd point'] 
    return ((p1[0] - p2[0])**2  + (p1[1] - p2[1])**2 )**0.5

In [387]:
euclidian_distance(points_df.iloc[0])

6.0

In [388]:
points_df.apply(euclidian_distance, axis=1)

0     6.000000
1     7.810250
2     2.828427
3    21.931712
4     5.000000
dtype: float64